insert into cities (name,ibge,state,country,capital) values ('Porto Velho',1100205,'Rondônia','br',true);
insert into cities (name,ibge,state,country,capital) values ('Manaus',1302603,'Amazonas','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Rio branco',1200401,'Acre','br',true);
insert into cities (name,ibge,state,country,capital) values ('Campo Grande',5002704,'Mato Grosso do Sul','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Macapá',1600303,'Amapá','br',true);	
insert into cities (name,ibge,state,country,capital) values ('brasília',5300108,'Distrito Federal','br',true);
insert into cities (name,ibge,state,country,capital) values ('Boa Vista',1400100,'Roraima','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Cuiabá',5103403,'Mato Grosso','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Palmas',1721000,'Tocantins','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Teresina',2211001,'Piauí','br',true);	
insert into cities (name,ibge,state,country,capital) values ('São Paulo',3550308,'São Paulo','br',true);
insert into cities (name,ibge,state,country,capital) values ('Rio de Janeiro',3304557,'Rio de Janeiro','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Belém',1501402,'Pará','br',true);	
insert into cities (name,ibge,state,country,capital) values ('São Luís',2111300,'Maranhão','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Goiânia',5208707,'Goiás','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Salvador',2927408,'Bahia Bahia','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Maceió',2704302,'Alagoas','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Porto Alegre','4314902','Rio Grande do Sul','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Curitiba',4106902,'Paraná','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Florianópolis',4205407,'Santa Catarina','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Belo Horizonte','3106200','Minas Gerais','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Fortaleza',2304400,'Ceará','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Recife',2611606,'Pernambuco','br',true);	
insert into cities (name,ibge,state,country,capital) values ('João Pessoa',2507507,'Paraíba','br',true);
insert into cities (name,ibge,state,country,capital) values ('Aracaju',2800308,'Sergipe','br',true);
insert into cities (name,ibge,state,country,capital) values ('Natal',2408102,'Rio Grande do Norte','br',true);	
insert into cities (name,ibge,state,country,capital) values ('Vitória',3205309,'Espirito Santo','br',true);
insert into cities (name,ibge,state,country,capital) values ('Caruaru',9999999,'Pernambuco','br',false);