DROP TABLE IF EXISTS CITIES;

CREATE TABLE CITIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ibge INT  NOT NULL UNIQUE,
  name VARCHAR(250) NOT NULL,
  state VARCHAR(250) NOT NULL,
  country VARCHAR(2) NOT NULL,
  capital BOOLEAN
);

