DROP TABLE IF EXISTS CITIES;
DROP TABLE IF EXISTS WEATHER_DATA;

CREATE TABLE CITIES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ibge INT  NOT NULL UNIQUE,
  name VARCHAR(250) NOT NULL,
  state VARCHAR(250) NOT NULL,
  country VARCHAR(2) NOT NULL,
  capital BOOLEAN
);

CREATE TABLE WEATHER_DATA (
   data TIMESTAMP NOT NULL,
   idCityApi INT NOT NULL,
   nameCity VARCHAR(250),
   cloudsPercent INT,
   weatherDescription VARCHAR(100),
   weatherIcon VARCHAR(30),
   temp DOUBLE,
   tempMin DOUBLE,
   tempMax DOUBLE,
   pressure DOUBLE,
   humidity DOUBLE,
   speedWind DOUBLE
 );
 
 ALTER TABLE WEATHER_DATA ADD PRIMARY KEY (data, idCityApi);
